Repository Plan-You/PlanU-FE, pull requests merged in 2024-11, with the labels that each got.

#9 chore: 백엔드 api url 추가 및 설정
  src/api/fetcher.ts
  src/vite-env.d.ts
  vite.config.ts
Labels: ⚙️ CHORE, 정재호

#11 chore: localhost https 적용 및 사용자 운영체제마다 다르게 mkcert 설치하는 방법 설정
  .gitignore
  init-https.sh
  package.json
  vercel.json
  vite.config.ts
Labels: ⚙️ CHORE, 정재호

#17 Fix: startPage margin-top 오류 수정
  .eslintrc.cjs
  .prettierrc.cjs
  README.md
  package-lock.json
  package.json
  src/App.module.scss
  src/App.tsx
  src/assets/logo/kakaoLogin.svg
  src/assets/logo/planU로고.svg
  src/index.scss
  src/layout/Layout.tsx
  src/layout/layout.module.scss
  src/main.tsx
  src/pages/StartPage/index.tsx
  src/pages/StartPage/startPage.module.scss
  tsconfig.app.json
Labels: ⚙️ CHORE, 🛠️ FIX, STYLE, 정재호

#19 fix: useNavigation
  .env.dev
  .gitignore
  src/App.module.css
  src/pages/RegisterAccountPage/page/index.tsx
  src/pages/RegisterAccountPage/page/register.module.scss
  src/pages/StartPage/index.tsx
Labels: 🛠️ FIX, 이수현

#22 Style : button components
  .eslintrc.cjs
  package-lock.json
  src/App.tsx
  src/assets/Icons/startPage/Icon_Kakao.svg
  src/assets/logo/kakaoLogin.svg
  src/components/buttons/DefaultButton.tsx
  src/components/buttons/GoLogin.tsx
  src/components/buttons/LoginButton.tsx
  src/components/buttons/SmallButton.tsx
  src/components/buttons/defaultButton.module.scss
  src/components/buttons/goLogin.module.scss
  src/components/buttons/loginBtn.module.scss
  src/components/buttons/smallButton.module.scss
  src/pages/LoginPage/components/SocialLoginButton.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/LoginPage/page/login.module.scss
  src/pages/RegisterAccountPage/page/index.tsx
  src/pages/RegisterPage/page/index.tsx
  src/pages/RegisterPage/page/register.module.scss
  src/pages/StartPage/index.tsx
  src/pages/StartPage/startPage.module.scss
Labels: STYLE, 이수현

#24 style: 버튼 컴포넌트에 대한 스토리북 파일 작성 완료
  .storybook/main.ts
  .storybook/preview.ts
  package-lock.json
  package.json
  src/App.tsx
  src/components/buttons/Button.stories.tsx
  src/components/buttons/goLogin.module.scss
  src/components/buttons/loginBtn.module.scss
Labels: 📜 DOCS, STYLE, 정재호

#30 Style : input component & register/login page 퍼블리싱
  .env.dev
  .eslintrc.cjs
  .prettierrc.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/assets/Icons/Icon_add.svg
  src/assets/Icons/Icon_alert.svg
  src/assets/Icons/Icon_calendar.svg
  src/assets/Icons/checkbox/Icon_checkBox_check.svg
  src/assets/Icons/checkbox/Icon_checkBox_uncheck.svg
  src/assets/Icons/eye/Icon_eyeOff.svg
  src/assets/Icons/eye/Icon_eyeOn.svg
  src/components/buttons/Button.stories.tsx
  src/components/buttons/CheckButton.tsx
  src/components/buttons/GoLogin.tsx
  src/components/buttons/MiniButton.tsx
  src/components/buttons/check.module.scss
  src/components/buttons/goLogin.module.scss
  src/components/buttons/loginBtn.module.scss
  src/components/buttons/mini.module.scss
  src/components/inputBoxes/Input.stories.tsx
  src/components/inputBoxes/LoginInput.tsx
  src/components/inputBoxes/loginInput.module.scss
  src/index.scss
  src/main.tsx
  src/pages/FindPage/page/index.tsx
  src/pages/LoginPage/components/FindComponent.tsx
  src/pages/LoginPage/components/find.module.scss
  src/pages/LoginPage/page/index.tsx
  src/pages/LoginPage/page/login.module.scss
  src/pages/RegisterPage/page/index.tsx
  src/pages/RegisterPage/page/register.module.scss
  src/pages/StartPage/index.tsx
  src/pages/StartPage/startPage.module.scss
  src/styles/variables.css
  tsconfig.json
Labels: 📜 DOCS, STYLE, 이수현

#31 Style: 각 페이지마다 쓰이는 헤더 컴포넌트 퍼블리싱 작업 및 스토리북 작성
  README.md
  src/App.tsx
  src/assets/Icons/headers/alertIcon.svg
  src/assets/Icons/headers/backArrow1.svg
  src/assets/Icons/headers/backArrow2.svg
  src/assets/Icons/headers/checkIcon.svg
  src/assets/Icons/headers/hamburgerIcon.svg
  src/assets/Icons/headers/miniCalender.svg
  src/assets/Icons/headers/moreIcon.svg
  src/assets/Icons/headers/redDot.svg
  src/assets/Icons/headers/searchIcon.svg
  src/assets/Icons/headers/xIcon.svg
  src/assets/images/cat.jpg
  src/components/buttons/Button.stories.tsx
  src/components/buttons/buttonStory.module.scss
  src/components/headers/CalenderHeader.tsx
  src/components/headers/HasOnlyBackArrowHeader.tsx
  src/components/headers/HasOnlyRightIconHeader.tsx
  src/components/headers/HasTwoIconHeader.tsx
  src/components/headers/Headers.stories.tsx
  src/components/headers/OnlyTextHeader.tsx
  src/components/headers/calenderHeader.module.scss
  src/components/headers/hasOnlyBackArrowHeader.module.scss
  src/components/headers/hasOnlyRightIconHeader.module.scss
  src/components/headers/hasTwoIconHeader.module.scss
  src/components/headers/headerStory.module.scss
  src/components/headers/onlyTextHeader.module.scss
  src/components/iconComponent/StarIcon.tsx
  src/pages/ChatListPage/components/ChatListHeader.tsx
  src/pages/ChatListPage/components/chatListHeader.module.scss
  src/pages/ChatListPage/page/index.tsx
  src/pages/ChatListSearchPage/components/ChatListSearchHeader.tsx
  src/pages/ChatListSearchPage/components/chatListSearchHeader.module.scss
  src/pages/ChatListSearchPage/page/index.tsx
  src/pages/ChattingPage/components/ChattingHeader.tsx
  src/pages/ChattingPage/components/chattingHeader.module.scss
Labels: 📜 DOCS, STYLE, 정재호

#35 Style : #26 하단 네비게이션 바 컴포넌트
  .eslintrc.cjs
  .prettierrc.cjs
  eslint.config.cjs
  package-lock.json
  package.json
  src/App.tsx
  src/assets/Icons/bottomNavBar/Calendar.svg
  src/assets/Icons/bottomNavBar/Users.svg
  src/assets/Icons/bottomNavBar/chat_bubble.svg
  src/assets/Icons/bottomNavBar/person.svg
  src/assets/logo/planU.svg
  src/components/BottomNavBar.tsx
  src/components/nav-bar/BottomNavBar.tsx
  src/components/nav-bar/bottomNavBar.module.scss
  src/components/nav-bar/nav-bar.stories.tsx
  src/main.tsx
  src/pages/StartPage/index.tsx
  tsconfig.json
Labels: ♻️ REFACTOR, STYLE, 정재호, 이다은

#37 Hotfix: 그룹 달력에서 사용되는 CalenderHeader 컴포넌트에서 점 세개 더보기 아이콘 삭제 및 헤더에 sticky 속성 추가
  src/components/headers/CalenderHeader.tsx
  src/components/headers/Headers.stories.tsx
  src/components/headers/calenderHeader.module.scss
  src/components/headers/hasOnlyBackArrowHeader.module.scss
  src/components/headers/hasOnlyRightIconHeader.module.scss
  src/components/headers/hasTwoIconHeader.module.scss
  src/components/headers/headerStory.module.scss
  src/components/headers/onlyTextHeader.module.scss
  src/pages/ChatListPage/components/chatListHeader.module.scss
  src/pages/ChatListSearchPage/components/chatListSearchHeader.module.scss
  src/pages/ChattingPage/components/chattingHeader.module.scss
Labels: 🚨 HOTFIX, STYLE, 정재호

#39 refactor & feat : inputComponent 회원가입 페이지 유효성 검사 api 연동작업
  package-lock.json
  package.json
  src/App.tsx
  src/api/apiRoutes.ts
  src/api/user/getCheckIdDuplication.ts
  src/api/user/postConfirmEmailCode.ts
  src/api/user/postEmailVerification.ts
  src/components/inputBoxes/Input.stories.tsx
  src/components/inputBoxes/LoginInput.tsx
  src/main.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/LoginPage/page/login.module.scss
  src/pages/MyCalendarPage/page/index.tsx
  src/pages/MyCalenderPage/page/index.tsx
  src/pages/RegisterPage/page/index.tsx
  src/pages/RegisterPage/page/register.module.scss
  src/types/post.d.ts
  src/types/response.d.ts
Labels: 🚀 FEAT, ♻️ REFACTOR, 이수현

#44 fix : 이메일 전송 api request params -> body로 변경
  src/api/user/postEmailVerification.ts
  src/pages/RegisterPage/page/index.tsx
Labels: 🚨 HOTFIX, 이수현

#42 Style: #40 그룹 생성 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/assets/Icons/Profile Picture/Icon_.pencil.svg
  src/assets/Icons/Profile Picture/Icon_camera.svg
  src/assets/Icons/Profile Picture/Icon_default_group.svg
  src/assets/Icons/Profile Picture/Icon_default_profile.svg
  src/components/buttons/DefaultButton.tsx
  src/pages/CreateGroupPage/components/GroupNameInput.stories.tsx
  src/pages/CreateGroupPage/components/GroupNameInput.tsx
  src/pages/CreateGroupPage/components/ImageUploader.stories.tsx
  src/pages/CreateGroupPage/components/ImageUploader.tsx
  src/pages/CreateGroupPage/components/groupNameInput.module.scss
  src/pages/CreateGroupPage/components/imageUploader.module.scss
  src/pages/CreateGroupPage/page/createGroup.module.scss
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/GroupPage/page/index.tsx
Labels: STYLE, 이다은
