Repository Plan-You/PlanU-FE, pull requests merged in 2024-12, with the labels that each got.

#45 Style: 회원정보 등록 페이지 퍼블리싱
  src/App.tsx
  src/assets/Icons/arrow/BottomArrow.svg
  src/assets/Icons/arrow/RightArrow.svg
  src/assets/Icons/arrow/TopArrow.svg
  src/components/Header.tsx
  src/pages/CreateGroupPage/components/ImageUploader.tsx
  src/pages/CreateGroupPage/components/imageUploader.module.scss
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/RegisterAccountPage/components/DatePicker.tsx
  src/pages/RegisterAccountPage/components/DatePickerComponent.stories.tsx
  src/pages/RegisterAccountPage/components/datePicker.module.scss
  src/pages/RegisterAccountPage/page/index.tsx
  src/pages/RegisterAccountPage/page/registerAccount.module.scss
Labels: 🛠️ FIX, STYLE, 정재호

#51 Feat: ImageUploader 컴포넌트에 이미지 유효성 검사 로직 추가
  src/pages/CreateGroupPage/components/ImageUploader.tsx
Labels: 🚀 FEAT, 정재호

#49 Hotfix: CalenderHeader props에 따른 아이콘 보여주는 로직 수정 및 타 헤더 수정
  src/assets/Icons/headers/miniCalender.svg
  src/components/headers/CalenderHeader.tsx
  src/components/headers/HasOnlyRightIconHeader.tsx
  src/components/headers/Headers.stories.tsx
  src/components/headers/calenderHeader.module.scss
  src/components/headers/hasOnlyRightIconHeader.module.scss
Labels: 🚨 HOTFIX, STYLE, 정재호

#54 Style: 초대 모달 퍼블리싱 작업
  .gitignore
  src/api/apiRoutes.ts
  src/api/user/postUserInformation.ts
  src/components/modals/InviteModal.tsx
  src/components/modals/Modal.stories.tsx
  src/components/modals/inviteModal.module.scss
  src/pages/CreateGroupPage/components/GroupNameInput.tsx
  src/pages/CreateGroupPage/components/ImageUploader.tsx
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/RegisterAccountPage/components/DatePicker.tsx
  src/pages/RegisterAccountPage/page/index.tsx
  src/types/post.d.ts
Labels: STYLE, 정재호

#57 Feat : 회원가입 페이지 api 연동
  src/App.tsx
  src/api/user/getCheckIdDuplication.ts
  src/api/user/posRegister.ts
  src/api/user/postConfirmEmailCode copy 2.ts
  src/api/user/postEmailVerification.ts
  src/api/user/postLogin.ts
  src/assets/Icons/registerSuccessPage/registerSuccessIcon.svg
  src/components/inputBoxes/LoginInput.tsx
  src/constants/validation.ts
  src/pages/LoginPage/page/index.tsx
  src/pages/RegisterPage/page/index.tsx
  src/pages/RegisterPage/page/register.module.scss
  src/pages/RegisterSuccessPage/page/inedx.tsx
  src/types/form.d.ts
  src/types/post.d.ts
Labels: 🚀 FEAT, 이수현

#60 Feat: 토큰 만료에 따른 갱신 api 연동 로직 작성
  src/api/apiRoutes.ts
  src/api/fetcher.ts
  src/api/user/getIsExistUserProfile.ts
  src/api/user/postLogin.ts
  src/api/user/postReissue.ts
  src/pages/LoginPage/components/FindComponent.tsx
  src/pages/LoginPage/page/index.tsx
Labels: 🚀 FEAT, 🛠️ FIX, 정재호

#64 Feat: 회원정보조회 api 연동 로직 작성 및 회원정보등록, 조회 api 연동 확인
  src/api/apiRoutes.ts
  src/api/user/getUserInfo.ts
  src/api/user/postUserInformation.ts
  src/pages/RegisterAccountPage/page/index.tsx
Labels: 🚀 FEAT, 🛠️ FIX, 정재호

#66 Style: 회원가입 성공 페이지 퍼블리싱
  src/api/user/postUserInformation.ts
  src/pages/RegisterSuccessPage/page/inedx.tsx
  src/pages/RegisterSuccessPage/page/registerSuccess.module.scss
Labels: 🚨 HOTFIX, STYLE, 정재호

#70 feat: 백엔드에서 보내주는 에러(resultMsg)만 따로 빼는 에러 핸들링 로직 작성
  src/api/fetcher.ts
  src/api/user/postLogin.ts
  src/api/user/postReissue.ts
  src/api/user/postUserInformation.ts
  src/pages/LoginPage/page/index.tsx
  src/pages/RegisterPage/page/index.tsx
Labels: 🚀 FEAT, 정재호

#74 Feat: 아이디/비밀번호 찾기 페이지 api 연동
  src/api/apiRoutes.ts
  src/api/user/postFindId.ts
  src/api/user/postFindPw.ts
  src/components/buttons/Button.stories.tsx
  src/components/buttons/DefaultButton.tsx
  src/components/buttons/defaultButton.module.scss
  src/pages/FindPage/components/FindInput.stories.tsx
  src/pages/FindPage/components/FindInput.tsx
  src/pages/FindPage/components/findInput.module.scss
  src/pages/FindPage/page/find.module.scss
  src/pages/FindPage/page/index.tsx
  src/pages/RegisterPage/page/index.tsx
  src/styles/variables.css
  src/types/inputLists.ts
Labels: 🚀 FEAT, 이수현

#75 Style: 그룹 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/api/fetcher.ts
  src/assets/Icons/groupPage/calendarIcon.svg
  src/assets/Icons/groupPage/chattingIcon.svg
  src/assets/Icons/groupPage/locationMarkerIcon.svg
  src/assets/Icons/groupPage/memberIcon.svg
  src/assets/Icons/groupPage/moneyIcon.svg
  src/assets/Icons/groupPage/postIcon.svg
  src/assets/Icons/groupPage/smallMoneyIcon.svg
  src/components/buttons/loginBtn.module.scss
  src/components/nav-bar/BottomNavBar.tsx
  src/components/nav-bar/bottomNavBar.module.scss
  src/constants/formatDate.ts
  src/constants/routingUrl.ts
  src/constants/truncation.ts
  src/index.scss
  src/layout/layout.module.scss
  src/pages/GroupPage/components/GroupOptions.tsx
  src/pages/GroupPage/components/GroupScheduleCalendar.tsx
  src/pages/GroupPage/components/TodayScheduleItem.tsx
  src/pages/GroupPage/components/TodayScheduleList.tsx
  src/pages/GroupPage/components/groupOptions.module.scss
  src/pages/GroupPage/components/groupScheduleCalendar.module.scss
  src/pages/GroupPage/components/todayScheduleItem.module.scss
  src/pages/GroupPage/components/todayScheduleList.module.scss
  src/pages/GroupPage/page/groupPage.module.scss
  src/pages/GroupPage/page/index.tsx
  src/pages/LoginPage/page/login.module.scss
  src/pages/MyPage/page/index.tsx
  src/pages/MyPage/page/myPage.module.scss
  src/pages/RegisterSuccessPage/page/index.tsx
  src/routes/ProtectedRoute.tsx
  src/store/useBottomStore.ts
  src/types/get.d.ts
Labels: 🚀 FEAT, 🛠️ FIX, STYLE, 정재호

#77 hotfix: 로그인 상태 여부 검사하는 로직 수정
  src/routes/CommonRoute.tsx
  src/routes/ProtectedRoute.tsx
Labels: 🚀 FEAT, 🚨 HOTFIX, 정재호
