Repository Plan-You/PlanU-FE, pull requests merged in 2025-06, with the labels that each got.

#246 Bug: 실시간 위치 공유 페이지에서 위치 초기화되는 에러 수정
  src/api/googleMapLoader.ts
  src/components/createSchedule/MemberBox.tsx
  src/components/createSchedule/ParticipantsPicker.tsx
  src/components/map/Map.tsx
  src/pages/EditSchedulePage/page/index.tsx
  src/pages/LocationSharingPage/page/index.tsx
  src/pages/SelectLocationPage/page/index.tsx
Labels: 🐛 BUG, 🛠️ FIX, 정재호

#247 Fix: 채팅관련 ui 수정
  src/pages/ChatListPage/components/ChatItem.tsx
  src/pages/ChatListPage/components/chatItem.module.scss
  src/pages/ChattingPage/components/ChatBubble.tsx
  src/pages/ChattingPage/components/chatBubble.module.scss
  src/pages/ChattingPage/components/sendMessage.module.scss
Labels: 🛠️ FIX, STYLE, 이수현

#248 DEploy: 채팅관련 ui 수정
  src/api/googleMapLoader.ts
  src/components/createSchedule/MemberBox.tsx
  src/components/createSchedule/ParticipantsPicker.tsx
  src/components/map/Map.tsx
  src/pages/ChatListPage/components/ChatItem.tsx
  src/pages/ChatListPage/components/chatItem.module.scss
  src/pages/ChattingPage/components/ChatBubble.tsx
  src/pages/ChattingPage/components/chatBubble.module.scss
  src/pages/ChattingPage/components/sendMessage.module.scss
  src/pages/EditSchedulePage/page/index.tsx
  src/pages/LocationSharingPage/page/index.tsx
  src/pages/SelectLocationPage/page/index.tsx
Labels: DEPLOY, STYLE, 이수현
