Repository Plan-You/PlanU-FE, pull requests merged in 2025-04, with the labels that each got.

#191 Fix: 종일 일정 시간 수정
  src/api/schedule/deleteComment.ts
  src/api/schedule/getComments.ts
  src/api/schedule/postComment.ts
  src/assets/Icons/scheduleDetail/Icon_trashcan.svg
  src/components/calendarPage/EventCard.tsx
  src/components/modals/AlertModal.tsx
  src/components/scheduleDetail/Boxes.module.scss
  src/components/scheduleDetail/Comment.module.scss
  src/components/scheduleDetail/CommentModal.tsx
  src/components/scheduleDetail/MoreModal.tsx
  src/pages/CreateSchedulePage/page/index.tsx
  src/pages/GroupScheduleDetailPage/page/index.tsx
  src/pages/MyScheduleDetailPage/page/index.tsx
  src/types/calendar.d.ts
Labels: 🛠️ FIX, STYLE, 이수현

#202 Bug: kakao 로그인을 한 첫 사용자는 사용자 정보 등록 페이지로 안넘어가던 오류 및 몇가지 오류 수정
  src/App.tsx
  src/components/calendarPage/EventCard.tsx
  src/components/headers/CalendarHeader.tsx
  src/pages/FriendManagementPage/components/MemberCard.tsx
  src/pages/MyCalendarPage/page/index.tsx
  src/pages/RegisterAccountPage/page/index.tsx
Labels: 🐛 BUG, 정재호

#205 Feat: 마이페이지 - 추천 친구 api 연동
  src/api/apiRoutes.ts
  src/api/friend/getRecommendedFriendList.ts
  src/pages/FriendManagementPage/page/friendManagementPage.module.scss
  src/pages/FriendManagementPage/page/index.tsx
  src/types/friend.d.ts
Labels: 🚀 FEAT, 이다은

#187 Feat: 나의 달력 - 가능한 날짜 api 연동
  src/api/apiRoutes.ts
  src/api/calendar/getMyAvailableDates.ts
  src/api/calendar/postMyAvailableDates.ts
  src/components/calendar/Calendar.tsx
  src/components/calendarPage/EventCard.tsx
  src/components/headers/hasOnlyBackArrowHeader.module.scss
  src/components/headers/hasOnlyRightIconHeader.module.scss
  src/components/headers/hasTwoIconHeader.module.scss
  src/components/headers/onlyTextHeader.module.scss
  src/constants/holidays.ts
  src/pages/MyCalendarPossiblePage/page/index.tsx
  src/pages/MyCalendarPossiblePage/page/myCalendarPossible.module.scss
  src/types/calendar.d.ts
Labels: 🚀 FEAT, 이다은

#207 Feat: 채팅 페이지 웹 소켓 STOMP, api 연동
  package-lock.json
  package.json
  src/api/apiRoutes.ts
  src/api/chat/getChatMessages.ts
  src/api/chat/getNewChatNumber.ts
  src/api/chat/getUpdateChatMessages copy.ts
  src/assets/Icons/chatt/IconSendMessageButton.svg
  src/components/nav-bar/BottomNavBar.tsx
  src/components/nav-bar/bottomNavBar.module.scss
  src/components/scheduleDetail/CommentModal.tsx
  src/pages/ChatListPage/components/ChatItem.tsx
  src/pages/ChatListPage/components/chatItem.module.scss
  src/pages/ChatListPage/page/index.tsx
  src/pages/ChattingPage/components/ChatBubble.tsx
  src/pages/ChattingPage/components/chatBubble.module.scss
  src/pages/ChattingPage/components/chattingHeader.module.scss
  src/pages/ChattingPage/page/chatPage.module.scss
  src/pages/ChattingPage/page/index.tsx
  src/pages/LoginPage/page/index.tsx
  src/store/useAuthStore.ts
  src/types/chatting.d.ts
  vite.config.ts
Labels: 🚀 FEAT, STYLE, 이수현

#221 style & feat: 그룹 일정 조회 페이지에 실시간 위치 공유 페이지로 이동하는 버튼 추가 및 조건 로직 추가
  src/App.tsx
  src/components/createSchedule/Inputs.module.scss
  src/components/createSchedule/MemberBox.tsx
  src/components/scheduleDetail/Boxes.module.scss
  src/components/scheduleDetail/LocationBox.tsx
  src/pages/GroupScheduleDetailPage/page/index.tsx
Labels: 🚀 FEAT, STYLE, 정재호

#228 Feat: 채팅방 이미지 전송 로직 작성 & 이미지 전송 부분 퍼블리싱
  src/api/apiRoutes.ts
  src/api/chat/postSendImage.ts
  src/assets/Icons/chatt/button.svg
  src/assets/Icons/chatt/mic.svg
  src/assets/Icons/chatt/photo.svg
  src/pages/ChatListPage/components/ChatItem.tsx
  src/pages/ChatListPage/components/chatItem.module.scss
  src/pages/ChattingPage/components/BottomMenuBox.tsx
  src/pages/ChattingPage/components/ChatBubble.tsx
  src/pages/ChattingPage/components/SendMessageInput.tsx
  src/pages/ChattingPage/components/bottomMenu.module.scss
  src/pages/ChattingPage/components/chatBubble.module.scss
  src/pages/ChattingPage/components/sendMessage.module.scss
  src/pages/ChattingPage/page/chatPage.module.scss
  src/pages/ChattingPage/page/index.tsx
  src/types/chatting.d.ts
Labels: 🚀 FEAT, STYLE, 이수현

#226 Fix: 일정 생성 관련 수정
  src/api/friend/getFriendList.ts
  src/api/group/getGroupMemberList.ts
  src/components/createSchedule/LocationBox.tsx
  src/components/createSchedule/MemberBox.tsx
  src/components/createSchedule/ParticipantsPicker.tsx
  src/components/createSchedule/participants.module.scss
  src/components/headers/hasOnlyBackArrowHeader.module.scss
  src/components/nav-bar/BottomNavBar.tsx
  src/components/scheduleDetail/CommentModal.tsx
  src/components/scheduleDetail/LocationBox.tsx
  src/pages/CreateSchedulePage/page/index.tsx
  src/pages/GroupScheduleDetailPage/page/index.tsx
  src/pages/MyPage/components/ButtonSection.tsx
  src/pages/MyPage/components/ProfileSection.tsx
  src/pages/MyPage/components/buttonSection.module.scss
  src/pages/MyPage/components/profileSection.module.scss
  src/pages/MyScheduleDetailPage/page/index.tsx
  src/types/calendar.d.ts
Labels: 🚀 FEAT, 🛠️ FIX, 이수현

#225 style: 내 달력, 그룹달력에서 클릭된 날짜는 배경색이 하이라이트 되도록 스타일 추가
  src/components/calendar/Calendar.tsx
  src/pages/GroupCalendarPage/page/index.tsx
  src/pages/MyCalendarPage/page/index.tsx
Labels: STYLE, 정재호

#229 Hotfix: build 에러 수정 및 사라진 파일 추가
  src/components/scheduleDetail/LocationBox.tsx
  src/pages/ChatListPage/components/ChatItem.tsx
  src/pages/EditSchedulePage/page/index.tsx
  src/pages/MyPage/components/ButtonSection.tsx
  src/pages/MyPage/components/ProfileSection.tsx
  src/pages/MyPage/components/buttonSection.module.scss
  src/pages/MyPage/components/profileSection.module.scss
Labels: DEPLOY, 🛠️ FIX, 🚨 HOTFIX, 이수현

#230 Deploy: 배포
  src/App.tsx
  src/api/apiRoutes.ts
  src/api/chat/postSendImage.ts
  src/api/friend/getFriendList.ts
  src/api/group/getGroupMemberList.ts
  src/assets/Icons/chatt/button.svg
  src/assets/Icons/chatt/mic.svg
  src/assets/Icons/chatt/photo.svg
  src/components/calendar/Calendar.tsx
  src/components/createSchedule/ChangeColorBox.tsx
  src/components/createSchedule/ColorBox.tsx
  src/components/createSchedule/Inputs.module.scss
  src/components/createSchedule/LocationBox.tsx
  src/components/createSchedule/MemberBox.tsx
  src/components/createSchedule/ParticipantsPicker.tsx
  src/components/createSchedule/changeColorBox.module.scss
  src/components/createSchedule/participants.module.scss
  src/components/headers/hasOnlyBackArrowHeader.module.scss
  src/components/nav-bar/BottomNavBar.tsx
  src/components/scheduleDetail/Boxes.module.scss
  src/components/scheduleDetail/CommentModal.tsx
  src/components/scheduleDetail/LocationBox.tsx
  src/pages/ChatListPage/components/chatItem.module.scss
  src/pages/ChattingPage/components/BottomMenuBox.tsx
  src/pages/ChattingPage/components/ChatBubble.tsx
  src/pages/ChattingPage/components/SendMessageInput.tsx
  src/pages/ChattingPage/components/bottomMenu.module.scss
  src/pages/ChattingPage/components/chatBubble.module.scss
  src/pages/ChattingPage/components/sendMessage.module.scss
  src/pages/ChattingPage/page/chatPage.module.scss
  src/pages/ChattingPage/page/index.tsx
  src/pages/CreateSchedulePage/page/index.tsx
  src/pages/EditSchedulePage/page/index.tsx
  src/pages/GroupCalendarPage/page/index.tsx
  src/pages/GroupScheduleDetailPage/page/index.tsx
  src/pages/MyCalendarPage/page/index.tsx
  src/pages/MyScheduleDetailPage/page/index.tsx
  src/store/useScheduleStore.ts
  src/types/calendar.d.ts
  src/types/chatting.d.ts
Labels: DEPLOY, 정재호

#231 fix: alert알림 toast알림으로 일괄 수정
  src/components/createSchedule/DatePicker.tsx
  src/components/createSchedule/TimePicker.tsx
  src/pages/ChattingPage/components/BottomMenuBox.tsx
  src/pages/CreateGroupPage/components/ImageUploader.tsx
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/EditProfilePage/page/index.tsx
  src/pages/FindPage/page/index.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/RegisterAccountPage/page/index.tsx
  src/pages/RegisterPage/page/index.tsx
Labels: 🛠️ FIX, STYLE, 정재호

#232 Deploy: alert 알림 toast 알림으로 일괄 수정
  src/components/createSchedule/DatePicker.tsx
  src/components/createSchedule/TimePicker.tsx
  src/pages/ChattingPage/components/BottomMenuBox.tsx
  src/pages/CreateGroupPage/components/ImageUploader.tsx
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/EditProfilePage/page/index.tsx
  src/pages/FindPage/page/index.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/RegisterAccountPage/page/index.tsx
  src/pages/RegisterPage/page/index.tsx
Labels: DEPLOY, STYLE, 정재호
