Repository Plan-You/PlanU-FE, pull requests merged in 2025-03, with the labels that each got.

#151 Feat: 그룹 달력 페이지 api 연동(그룹 달력 일정 유무 조회, 그룹 달력 일정 조회)
  src/api/calendar/getGroupCalendarCheckEvents.ts
  src/api/calendar/getGroupScheduleList.ts
  src/api/group/getGroupCalendarSchedules.ts
  src/api/group/getGroupDetail.ts
  src/api/group/getGroupMemberInviteList.ts
  src/api/group/getGroupMemberList.ts
  src/api/group/getGroupTodaySchedules.ts
  src/components/calendar/Calendar.tsx
  src/pages/GroupCalendarPage/page/index.tsx
  src/pages/GroupCalendarPossiblePage/page/index.tsx
  src/pages/GroupPage/page/index.tsx
  src/pages/MyCalendarPage/page/index.tsx
  src/types/calendar.d.ts
  src/types/get.d.ts
Labels: 🚀 FEAT, 🛠️ FIX, 정재호

#155 Feat: 채팅방목록 페이지 api 연동
  src/api/apiRoutes.ts
  src/api/chat/getChatRoomList.ts
  src/api/user/postConfirmEmailCode.ts
  src/pages/ChatListPage/components/ChatItem.tsx
  src/pages/ChatListPage/page/index.tsx
  src/pages/FindPage/page/index.tsx
  src/pages/GroupListPage/page/groupList.module.scss
  src/pages/RegisterPage/page/index.tsx
  src/types/chatting.d.ts
  src/types/inputLists.ts
  src/types/user.d.ts
Labels: 🚀 FEAT, 이수현

#160 Style: 마이페이지 친구관리 추가 페이지 퍼블리싱
  src/api/schedule/group/deleteForcedWithdrawalFromGroup.ts
  src/api/schedule/group/deleteGroup.ts
  src/api/schedule/group/deleteInviteGroupMember.ts
  src/api/schedule/group/deleteLeaveGroup.ts
  src/api/schedule/group/getGroupCalendarSchedules.ts
  src/api/schedule/group/getGroupDetail.ts
  src/api/schedule/group/getGroupInviteList.ts
  src/api/schedule/group/getGroupList.ts
  src/api/schedule/group/getGroupMemberInviteList.ts
  src/api/schedule/group/getGroupMemberList.ts
  src/api/schedule/group/getGroupTodaySchedules.ts
  src/api/schedule/group/patchGroupPin.ts
  src/api/schedule/group/postCreateGroup.ts
  src/api/schedule/group/postCreateGroupSchedule.ts
  src/api/schedule/group/postInviteGroupMember.ts
  src/api/schedule/group/putGroupInviteAcceptOrReject.ts
  src/assets/Icons/Icon_addFriend.svg
  src/assets/Icons/myPage/add.svg
  src/components/buttons/Button.stories.tsx
  src/components/buttons/MiniButton.tsx
  src/components/createSchedule/MemberBox.tsx
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/EditProfilePage/page/index.tsx
  src/pages/FriendManagementPage/components/MemberCard.tsx
  src/pages/FriendManagementPage/page/friendManagementPage.module.scss
  src/pages/FriendManagementPage/page/index.tsx
  src/pages/GroupListPage/page/index.tsx
  src/pages/GroupMemberPage/components/MemberItem.tsx
  src/pages/GroupMemberPage/page/index.tsx
  src/pages/GroupPage/page/index.tsx
  src/pages/InviteGroupMemberPage/page/index.tsx
Labels: STYLE, 이다은

#161 Style: 알림 페이지 퍼블리싱 작업
  src/App.tsx
  src/api/apiRoutes.ts
  src/api/group/deleteForcedWithdrawalFromGroup.ts
  src/api/group/deleteGroup.ts
  src/api/group/deleteInviteGroupMember.ts
  src/api/group/deleteLeaveGroup.ts
  src/api/group/getGroupCalendarSchedules.ts
  src/api/group/getGroupDetail.ts
  src/api/group/getGroupInviteList.ts
  src/api/group/getGroupList.ts
  src/api/group/getGroupMemberInviteList.ts
  src/api/group/getGroupMemberList.ts
  src/api/group/getGroupTodaySchedules.ts
  src/api/group/patchGroupPin.ts
  src/api/group/postCreateGroup.ts
  src/api/group/postCreateGroupSchedule.ts
  src/api/group/postInviteGroupMember.ts
  src/api/group/putGroupInviteAcceptOrReject.ts
  src/api/notification/postReadNotification.ts
  src/assets/Icons/alert/defaultAlert.svg
  src/components/createSchedule/DatePicker.tsx
  src/components/createSchedule/MemberBox.tsx
  src/pages/ChatListPage/page/index.tsx
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/GroupListPage/page/index.tsx
  src/pages/GroupMemberPage/components/MemberItem.tsx
  src/pages/GroupMemberPage/page/index.tsx
  src/pages/GroupPage/page/index.tsx
  src/pages/InviteGroupMemberPage/page/index.tsx
  src/pages/NotificationPage/components/NotificationItem.tsx
  src/pages/NotificationPage/components/NotificationList.tsx
  src/pages/NotificationPage/components/notificationItem.module.scss
  src/pages/NotificationPage/components/notificationList.module.scss
  src/pages/NotificationPage/page/index.tsx
  src/pages/NotificationPage/page/notification.module.scss
  src/types/alert.d.ts
Labels: STYLE, 정재호

#163 Feat: 그룹 일정 상세 페이지 api 연동
  src/api/chat/getChatRoomList.ts
  src/api/schedule/getGroupScheduleDetail.ts
  src/api/schedule/getMyScheduleDetail.ts
  src/components/calendarPage/EventCard.tsx
  src/pages/GroupScheduleDetailPage/page/groupSchedule.module.scss
  src/pages/GroupScheduleDetailPage/page/index.tsx
  src/pages/MyScheduleDetailPage/components/Boxes.module.scss
  src/pages/MyScheduleDetailPage/components/LocationBox.tsx
  src/pages/MyScheduleDetailPage/components/MemoBox.tsx
  src/pages/MyScheduleDetailPage/components/ParticipantsBox.tsx
  src/pages/MyScheduleDetailPage/components/TimeBox.tsx
  src/pages/MyScheduleDetailPage/components/TitleBox.tsx
  src/pages/MyScheduleDetailPage/page/index.tsx
  src/types/calendar.d.ts
Labels: 🚀 FEAT, STYLE, 이수현

#172 Feat: 알림 페이지 sse 실시간 연동
  src/api/apiRoutes.ts
  src/api/notification/getNotificationList.ts
  src/api/notification/getSubscribeToSSE.ts
  src/api/notification/postReadNotification.ts
  src/components/headers/HasOnlyRightIconHeader.tsx
  src/pages/ChatListPage/components/ChatListHeader.tsx
  src/pages/ChatListPage/page/index.tsx
  src/pages/GroupListPage/page/index.tsx
  src/pages/NotificationPage/components/NotificationItem.tsx
  src/pages/NotificationPage/components/NotificationList.tsx
  src/pages/NotificationPage/page/index.tsx
  src/pages/NotificationPage/utils/getRelativeTime.ts
  src/pages/NotificationPage/utils/notificationType.ts
  src/routes/ProtectedRoute.tsx
  src/types/alert.d.ts
Labels: 🚀 FEAT, 정재호

#179 Feat: 카카오 로그인 연동
  src/api/apiRoutes.ts
  src/api/notification/getSubscribeToSSE.ts
  src/api/notification/postReadAllNotifications.ts
  src/components/headers/HasOnlyBackArrowHeader.tsx
  src/components/headers/hasOnlyBackArrowHeader.module.scss
  src/pages/LoginPage/page/index.tsx
  src/pages/MyCalendarPage/page/index.tsx
  src/pages/MyCalendarPossiblePage/page/index.tsx
  src/pages/MyCalendarPossiblePage/page/myCalendarPossible.module.scss
  src/pages/NotificationPage/page/index.tsx
  src/pages/StartPage/index.tsx
  src/routes/ProtectedRoute.tsx
  src/types/notification.d.ts
Labels: 🚀 FEAT, 정재호

#171 Feat: 마이페이지 설정 api 연동
  src/api/apiRoutes.ts
  src/api/user/postChangePassword.ts
  src/api/user/postVerifyPassword.ts
  src/api/user/putUserInfo.ts
  src/components/buttons/SmallButton.tsx
  src/pages/EditProfilePage/components/InlineEditableProfileItem.tsx
  src/pages/EditProfilePage/components/InlineEditableProfileItemWithButton.tsx
  src/pages/EditProfilePage/components/ModalEditableProfileItem.tsx
  src/pages/EditProfilePage/page/index.tsx
  src/pages/RegisterAccountPage/components/DatePicker.tsx
  src/types/edit.d.ts
Labels: 🚀 FEAT, 이다은

#183 feat: 나의 달력 페이지 api 연동
  src/App.tsx
  src/api/calendar/getMyCalendarCheckEvents.ts
  src/api/calendar/getMyScheduleList.ts
  src/pages/MyCalendarPage/page/index.tsx
  src/types/calendar.d.ts
Labels: 🚀 FEAT, 이다은

#185 Fix: 나의 달력 페이지 오류 수정
  src/App.tsx
  src/api/calendar/getMyScheduleList.ts
  src/components/calendar/Calendar.tsx
  src/pages/FriendManagementPage/components/MemberCard.tsx
  src/pages/MyCalendarPage/page/index.tsx
  src/types/calendar.d.ts
Labels: 🐛 BUG, 🛠️ FIX, 정재호

#182 style: 위치공유 페이지에서 참여자 목록의 참여자 클릭하면 border가 두꺼워지고 보라색으로 강조되도록 스타일 적용
  src/api/apiRoutes.ts
  src/pages/LocationSharingPage/components/GroupMemberItem.tsx
  src/pages/LocationSharingPage/components/groupMemberItem.module.scss
  src/pages/LocationSharingPage/page/index.tsx
  src/pages/LocationSharingPage/page/locationSharing.module.scss
  src/types/locationInfo.d.ts
Labels: STYLE, 정재호
