Repository Plan-You/PlanU-FE, pull requests merged in 2025-02, with the labels that each got.

#139 Fix: api 호출 후 reset State
  src/api/schedule/postCreateGroupSchedule.ts
  src/api/schedule/postCreateMySchedule.ts
  src/components/createSchedule/MemberBox.tsx
  src/components/createSchedule/ParticipantsPicker.tsx
  src/pages/CreateSchedulePage/page/index.tsx
  src/pages/EditSchedulePage/page/index.tsx
  src/store/useScheduleStore.ts
Labels: 🛠️ FIX, 이수현

#141 Feat: 그룹 상대 추가 목록 페이지 api 연동(그룹 상대 추가 목록 조회, 그룹 멤버 초대, 그룹 멤버 초대 취소)
  package-lock.json
  package.json
  src/App.tsx
  src/api/group/deleteInviteGroupMember.ts
  src/api/group/getGroupMemberInviteList.ts
  src/api/group/postInviteGroupMember.ts
  src/api/user/getCheckIdDuplication.ts
  src/api/user/getUserInfo.ts
  src/components/headers/HasOnlyRightIconHeader.tsx
  src/components/headers/Headers.stories.tsx
  src/pages/EditProfilePage/components/BottomSheetModal.tsx
  src/pages/EditProfilePage/components/InlineEditableProfileItem.stories.tsx
  src/pages/EditProfilePage/components/InlineEditableProfileItem.tsx
  src/pages/EditProfilePage/components/InlineEditableProfileItemWithButton.stories.tsx
  src/pages/EditProfilePage/components/InlineEditableProfileItemWithButton.tsx
  src/pages/EditProfilePage/components/ModalEditableProfileItem.stories.tsx
  src/pages/EditProfilePage/components/ModalEditableProfileItem.tsx
  src/pages/EditProfilePage/components/bottomSheetModal.module.scss
  src/pages/EditProfilePage/components/inlineEditableProfileItem.module.scss
  src/pages/EditProfilePage/components/modalEditableProfileItem.module.scss
  src/pages/EditProfilePage/page/index.tsx
  src/pages/EditProfilePage/page/profileEditPage.module.scss
  src/pages/FindPage/page/find.module.scss
  src/pages/GroupMemberPage/page/index.tsx
  src/pages/InviteGroupMemberPage/components/FriendItem.tsx
  src/pages/InviteGroupMemberPage/components/FriendList.tsx
  src/pages/InviteGroupMemberPage/components/SearchBox.tsx
  src/pages/InviteGroupMemberPage/components/friendItem.module.scss
  src/pages/InviteGroupMemberPage/components/friendList.module.scss
  src/pages/InviteGroupMemberPage/page/index.tsx
  src/pages/InviteGroupMemberPage/page/inviteGroupMember.module.scss
  src/pages/ModifyMyAccountPage/page/index.tsx
  src/types/get.d.ts
  src/types/group.d.ts
Labels: 🚀 FEAT, ♻️ REFACTOR, 정재호

#142 Feat: 그룹 상세 페이지 api 연동(그룹 상세 조회, 그룹 상단 고정/해제, 그룹 일정 조회, 그룹 today일정 조회)
  package-lock.json
  package.json
  src/api/apiRoutes.ts
  src/api/group/getGroupCalendarSchedules.ts
  src/api/group/getGroupDetail.ts
  src/api/group/getGroupTodaySchedules.ts
  src/api/group/patchGroupPin.ts
  src/api/schedule/postCreateMySchedule.ts
  src/assets/Icons/groupPage/pinIcon.svg
  src/components/createSchedule/LocationBox.tsx
  src/components/headers/HasTwoIconHeader.tsx
  src/components/headers/Headers.stories.tsx
  src/components/iconComponent/StarIcon.tsx
  src/constants/holidays.ts
  src/pages/CreateSchedulePage/page/index.tsx
  src/pages/CreateSchedulePage/store/useCreateScheduleStore.ts
  src/pages/GroupListPage/components/GroupItem.tsx
  src/pages/GroupListPage/components/groupItem.module.scss
  src/pages/GroupPage/components/GroupScheduleCalendar.tsx
  src/pages/GroupPage/components/TodayScheduleList.tsx
  src/pages/GroupPage/components/groupScheduleCalendar.module.scss
  src/pages/GroupPage/components/todayScheduleList.module.scss
  src/pages/GroupPage/page/groupPage.module.scss
  src/pages/GroupPage/page/index.tsx
  src/pages/MyCalendarPage/page/index.tsx
  src/store/useScheduleStore.ts
  src/types/get.d.ts
  src/types/group.d.ts
Labels: 🚀 FEAT, 🛠️ FIX, 정재호

#144 feat: 마이페이지 api 연동
  src/api/friend/getFriendList.ts
  src/pages/FriendManagementPage/components/MemberCard.tsx
  src/pages/MyPage/components/ButtonSection.tsx
  src/pages/MyPage/components/ProfileSection.tsx
  src/pages/MyPage/components/profileSection.module.scss
  src/pages/MyPage/page/index.tsx
  src/pages/MyPage/page/myPage.module.scss
  src/pages/Mypage/components/ButtonSection.tsx
  src/pages/Mypage/components/ProfileSection.tsx
  src/pages/Mypage/components/profileSection.module.scss
Labels: 🚀 FEAT, 이다은

#145 Feat: 마이페이지-친구관리 api 연동
  src/api/friend/deleteCancelRequestFriend.ts
  src/api/friend/deleteDeleteFriends.ts
  src/api/friend/deleteRejectRequestFriend.ts
  src/api/friend/getFriendList.ts
  src/api/friend/getReceiveFriendList.ts
  src/api/friend/getRequestFriendList.ts
  src/api/friend/postAcceptRequestFriend.ts
  src/api/friend/postRequestFriend.ts
  src/pages/FriendManagementPage/components/IDInput.tsx
  src/pages/FriendManagementPage/components/MemberCard.tsx
  src/pages/FriendManagementPage/page/friendManagementPage.module.scss
  src/pages/FriendManagementPage/page/index.tsx
  src/types/friend.d.ts
Labels: 🚀 FEAT, 이다은

#150 Hotfix: 그룹 달력 총 일정 조회 api endpoint 수정에 따른 프론트로직 및 데이터타입 수정
  src/App.tsx
  src/api/group/getGroupCalendarSchedules.ts
  src/components/calendarPage/EventCard.tsx
  src/components/calendarPage/eventCard.module.scss
  src/components/headers/CalendarHeader.tsx
  src/components/headers/calendarHeader.module.scss
  src/pages/GroupCalendarPage/page/groupCalendarPage.module.scss
  src/pages/GroupCalendarPage/page/index.tsx
  src/pages/GroupPage/components/GroupScheduleCalendar.tsx
  src/pages/GroupPage/page/index.tsx
  src/pages/MyCalendarPage/page/index.tsx
  src/pages/MyCalendarPage/page/myCalendarPage.module.scss
  src/pages/MyPage/page/myPage.module.scss
  src/types/calendar.d.ts
  src/types/get.d.ts
  src/types/group.d.ts
Labels: 🚨 HOTFIX, 정재호
