Repository Plan-You/PlanU-FE, pull requests merged in 2025-05, with the labels that each got.

#235 Fix: 1차 QA 후 기능상 오류 수정
  src/App.tsx
  src/components/createSchedule/LocationBox.tsx
  src/components/createSchedule/MemberBox.tsx
  src/pages/ChattingPage/components/ChatBubble.tsx
  src/pages/ChattingPage/components/chatBubble.module.scss
  src/pages/ChattingPage/components/chattingHeader.module.scss
  src/pages/ChattingPage/page/chatPage.module.scss
  src/pages/ChattingPage/page/index.tsx
  src/pages/CreateSchedulePage/page/index.tsx
  src/pages/EditSchedulePage/page/editSchedule.module.scss
  src/pages/EditSchedulePage/page/index.tsx
  src/pages/GroupScheduleDetailPage/page/index.tsx
  src/store/useScheduleStore.ts
Labels: 🛠️ FIX, 이수현

#236 Fix: [1차 QA] 친구 및 마이페이지 관련 UI/기능 수정
  src/pages/EditProfilePage/page/index.tsx
  src/pages/FriendManagementPage/components/MemberCard.tsx
  src/pages/FriendManagementPage/components/memberCard.module.scss
  src/pages/FriendManagementPage/page/friendManagementPage.module.scss
  src/pages/FriendManagementPage/page/index.tsx
Labels: 🛠️ FIX, 이다은

#237 Fix: 1차 QA 오류 수정
  src/api/group/deleteForcedWithdrawalFromGroup.ts
  src/assets/Icons/startPage/Icon_Kakao.svg
  src/components/buttons/LoginButton.tsx
  src/components/createSchedule/LocationBox.tsx
  src/components/modals/AlertModal.module.scss
  src/components/modals/AlertModal.tsx
  src/components/scheduleDetail/Boxes.module.scss
  src/components/scheduleDetail/LocationBox.tsx
  src/pages/FriendManagementPage/page/friendManagementPage.module.scss
  src/pages/FriendManagementPage/page/index.tsx
  src/pages/GroupMemberPage/components/MemberItem.tsx
  src/pages/GroupPage/components/GroupOptions.tsx
  src/pages/GroupPage/page/groupPage.module.scss
  src/pages/GroupPage/page/index.tsx
  src/pages/GroupScheduleDetailPage/page/index.tsx
  src/pages/InviteGroupMemberPage/components/FriendItem.tsx
  src/pages/InviteGroupMemberPage/components/friendItem.module.scss
  src/pages/LocationSharingPage/page/index.tsx
  src/pages/RegisterAccountPage/components/DatePicker.tsx
  src/pages/RegisterAccountPage/components/datePicker.module.scss
  src/pages/SelectLocationPage/page/index.tsx
  src/store/useScheduleStore.ts
  src/store/webSocketProvider.tsx
  src/types/locationInfo.d.ts
  src/utils/drawMap.ts
  src/utils/geocoding.ts
Labels: 🐛 BUG, 🛠️ FIX, 정재호

#238 Deploy: 1차 QA 테스트 오류수정 및 개선사항 추가
  src/App.tsx
  src/api/group/deleteForcedWithdrawalFromGroup.ts
  src/assets/Icons/startPage/Icon_Kakao.svg
  src/components/buttons/LoginButton.tsx
  src/components/createSchedule/LocationBox.tsx
  src/components/createSchedule/MemberBox.tsx
  src/components/modals/AlertModal.module.scss
  src/components/modals/AlertModal.tsx
  src/components/scheduleDetail/Boxes.module.scss
  src/components/scheduleDetail/LocationBox.tsx
  src/pages/ChattingPage/components/ChatBubble.tsx
  src/pages/ChattingPage/components/chatBubble.module.scss
  src/pages/ChattingPage/components/chattingHeader.module.scss
  src/pages/ChattingPage/page/chatPage.module.scss
  src/pages/ChattingPage/page/index.tsx
  src/pages/CreateSchedulePage/page/index.tsx
  src/pages/EditProfilePage/page/index.tsx
  src/pages/EditSchedulePage/page/editSchedule.module.scss
  src/pages/EditSchedulePage/page/index.tsx
  src/pages/FriendManagementPage/components/MemberCard.tsx
  src/pages/FriendManagementPage/components/memberCard.module.scss
  src/pages/FriendManagementPage/page/friendManagementPage.module.scss
  src/pages/FriendManagementPage/page/index.tsx
  src/pages/GroupMemberPage/components/MemberItem.tsx
  src/pages/GroupPage/components/GroupOptions.tsx
  src/pages/GroupPage/page/groupPage.module.scss
  src/pages/GroupPage/page/index.tsx
  src/pages/GroupScheduleDetailPage/page/index.tsx
  src/pages/InviteGroupMemberPage/components/FriendItem.tsx
  src/pages/InviteGroupMemberPage/components/friendItem.module.scss
  src/pages/LocationSharingPage/page/index.tsx
  src/pages/RegisterAccountPage/components/DatePicker.tsx
  src/pages/RegisterAccountPage/components/datePicker.module.scss
  src/pages/SelectLocationPage/page/index.tsx
  src/store/useScheduleStore.ts
  src/store/webSocketProvider.tsx
  src/types/locationInfo.d.ts
  src/utils/drawMap.ts
  src/utils/geocoding.ts
Labels: DEPLOY, 🛠️ FIX, 정재호

#240 Fix: 2차 qa 오류 수정
  src/components/createSchedule/ChangeColorBox.tsx
  src/components/scheduleDetail/LocationBox.tsx
  src/pages/GroupMemberPage/page/groupMember.module.scss
  src/pages/GroupScheduleDetailPage/page/index.tsx
  src/pages/LocationSharingPage/page/index.tsx
  src/pages/SelectLocationPage/page/index.tsx
Labels: 🐛 BUG, 🛠️ FIX, 정재호

#242 Fix: 2차 QA 오류 수정
  src/pages/CreateGroupPage/components/imageUploader.module.scss
  src/pages/FriendManagementPage/page/friendManagementPage.module.scss
Labels: 🛠️ FIX, 이다은

#244 Deploy: 2차 qa 테스트 오류 수정 후 재배포
  src/components/createSchedule/ChangeColorBox.tsx
  src/components/createSchedule/Inputs.module.scss
  src/components/createSchedule/TimeBox.tsx
  src/components/scheduleDetail/LocationBox.tsx
  src/components/scheduleDetail/MoreModal.tsx
  src/components/scheduleDetail/TitleBox.tsx
  src/pages/ChattingPage/components/ChattingHeader.tsx
  src/pages/ChattingPage/page/chatPage.module.scss
  src/pages/CreateGroupPage/components/imageUploader.module.scss
  src/pages/FriendManagementPage/page/friendManagementPage.module.scss
  src/pages/GroupMemberPage/page/groupMember.module.scss
  src/pages/GroupScheduleDetailPage/page/index.tsx
  src/pages/LocationSharingPage/page/index.tsx
  src/pages/MyScheduleDetailPage/page/index.tsx
  src/pages/SelectLocationPage/page/index.tsx
Labels: DEPLOY, 정재호
