Repository Plan-You/PlanU-FE, pull requests merged in 2025-01, with the labels that each got.

#80 style: 그룹 목록 페이지 퍼블리싱
  src/assets/Icons/Icon_add_circle.svg
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/GroupListPage/components/GroupItem.tsx
  src/pages/GroupListPage/components/InviteItem.tsx
  src/pages/GroupListPage/components/groupItem.module.scss
  src/pages/GroupListPage/page/groupList.module.scss
  src/pages/GroupListPage/page/index.tsx
Labels: STYLE, 이수현

#83 Style: 그룹 멤버 초대 페이지 퍼블리싱
  src/App.tsx
  src/api/fetcher.ts
  src/assets/Icons/Icon_search.svg
  src/components/buttons/MiniButton.tsx
  src/components/buttons/goLogin.module.scss
  src/components/buttons/mini.module.scss
  src/components/buttons/smallButton.module.scss
  src/pages/InviteGroupMemberPage/components/FriendItem.tsx
  src/pages/InviteGroupMemberPage/components/FriendList.tsx
  src/pages/InviteGroupMemberPage/components/SearchBox.tsx
  src/pages/InviteGroupMemberPage/components/friendItem.module.scss
  src/pages/InviteGroupMemberPage/components/friendList.module.scss
  src/pages/InviteGroupMemberPage/components/searchBox.module.scss
  src/pages/InviteGroupMemberPage/page/index.tsx
  src/pages/InviteGroupMemberPage/page/inviteGroupMember.module.scss
  src/pages/SignUpPage/page/index.tsx
  src/types/get.d.ts
Labels: 🛠️ FIX, STYLE, 정재호

#85 Style: 그룹 멤버 목록 페이지 퍼블리싱
  src/assets/Icons/groupPage/checkIcon.svg
  src/assets/Icons/groupPage/crownIcon.svg
  src/assets/Icons/groupPage/smallCircleProfile.svg
  src/components/buttons/MiniButton.tsx
  src/components/buttons/mini.module.scss
  src/pages/GroupMemberPage/components/MemberItem.tsx
  src/pages/GroupMemberPage/components/MemberList.tsx
  src/pages/GroupMemberPage/components/memberItem.module.scss
  src/pages/GroupMemberPage/components/memberList.module.scss
  src/pages/GroupMemberPage/page/groupMember.module.scss
  src/pages/GroupMemberPage/page/index.tsx
  src/pages/InviteGroupMemberPage/page/inviteGroupMember.module.scss
  src/types/get.d.ts
Labels: STYLE, 정재호

#92 Style: 채팅 목록 페이지 퍼블리싱
  src/assets/Icons/chatt/pinned.svg
  src/assets/images/discord.jpg
  src/pages/ChatListPage/components/ChatItem.stories.tsx
  src/pages/ChatListPage/components/ChatItem.tsx
  src/pages/ChatListPage/components/chatItem.module.scss
  src/pages/ChatListPage/page/index.tsx
  src/pages/ChatListPage/page/messagesPage.module.scss
Labels: STYLE, 이다은

#89 Style: 마이페이지 설정 퍼블리싱
  src/App.tsx
  src/assets/Icons/ProfileItem/arrow.svg
  src/components/buttons/SmallButton.tsx
  src/pages/CreateGroupPage/components/imageUploader.module.scss
  src/pages/ModifyMyAccountPage/components/BottomSheetModal.tsx
  src/pages/ModifyMyAccountPage/components/InlineEditableProfileItem.stories.tsx
  src/pages/ModifyMyAccountPage/components/InlineEditableProfileItem.tsx
  src/pages/ModifyMyAccountPage/components/InlineEditableProfileItemWithButton.stories.tsx
  src/pages/ModifyMyAccountPage/components/InlineEditableProfileItemWithButton.tsx
  src/pages/ModifyMyAccountPage/components/ModalEditableProfileItem.stories.tsx
  src/pages/ModifyMyAccountPage/components/ModalEditableProfileItem.tsx
  src/pages/ModifyMyAccountPage/components/bottomSheetModal.module.scss
  src/pages/ModifyMyAccountPage/components/inlineEditableProfileItem.module.scss
  src/pages/ModifyMyAccountPage/components/modalEditableProfileItem.module.scss
  src/pages/ModifyMyAccountPage/page/index.tsx
  src/pages/ModifyMyAccountPage/page/profileEditPage.module.scss
  src/pages/RegisterAccountPage/components/DatePicker.tsx
Labels: STYLE, 이다은

#95 Style: 그룹 및 나의 달력 페이지에서 사용되는 달력 컴포넌트 퍼블리싱
  src/assets/Icons/calendar/isBirthdayIcon.svg
  src/assets/Icons/calendar/isScheduleIcon.svg
  src/components/calendar/Calendar.tsx
  src/components/calendar/calendar.module.scss
  src/components/calendar/calendar.stories.tsx
  src/constants/holidays.ts
  src/pages/GroupPage/components/GroupScheduleCalendar.tsx
  src/styles/variables.css
  src/types/get.d.ts
Labels: STYLE, 정재호

#98 Style: 채팅 목록 검색 페이지 퍼블리싱
  src/assets/Icons/Close/Icon_close.svg
  src/assets/images/CD.jpg
  src/assets/images/bubble.jpg
  src/pages/ChatListSearchPage/components/ProfileItem.tsx
  src/pages/ChatListSearchPage/components/profileItem.module.scss
  src/pages/ChatListSearchPage/page/chatListPage.module.scss
  src/pages/ChatListSearchPage/page/index.tsx
Labels: STYLE, 이다은

#100 style: 채팅 페이지 퍼블리싱
  src/assets/images/chat.jpg
  src/pages/ChattingPage/components/ChatBubble.tsx
  src/pages/ChattingPage/components/chatBubble.module.scss
  src/pages/ChattingPage/page/chatPage.module.scss
  src/pages/ChattingPage/page/index.tsx
Labels: STYLE, 이다은

#102 Style: 일정 생성 페이지에서 사용되는 지도 컴포넌트 퍼블리싱 및 기능 구현(google maps api 연동)
  package-lock.json
  package.json
  src/api/googleMapLoader.ts
  src/components/map/Map.stories.tsx
  src/components/map/Map.tsx
  src/components/map/map.module.scss
  src/constants/geocoding.ts
  src/types/global.d.ts
  src/types/locationInfo.d.ts
  tsconfig.app.json
Labels: 🚀 FEAT, STYLE, 정재호

#104 Style: 나의 달력 페이지 퍼블리싱
  src/assets/Icons/myCalendar/EditIcon.svg
  src/assets/Icons/myCalendar/location.svg
  src/pages/MyCalendarPage/components/EventCard.stories.tsx
  src/pages/MyCalendarPage/components/EventCard.tsx
  src/pages/MyCalendarPage/components/eventCard.module.scss
  src/pages/MyCalendarPage/page/index.tsx
  src/pages/MyCalendarPage/page/myCalendarPage.module.scss
Labels: STYLE, 이다은

#107 Style: 장소 선택 페이지 퍼블리싱 및 기능 구현
  src/api/googleMapLoader.ts
  src/assets/Icons/map/locationIcon.svg
  src/assets/Icons/map/selectedLocationIcon.svg
  src/components/buttons/Button.stories.tsx
  src/components/calendar/Calendar.tsx
  src/components/map/Map.tsx
  src/layout/layout.module.scss
  src/pages/FindPage/components/FindTypeTab.tsx
  src/pages/GroupPage/components/GroupScheduleCalendar.tsx
  src/pages/GroupPage/components/TodayScheduleItem.tsx
  src/pages/ModifyMyAccountPage/page/index.tsx
  src/pages/SelectLocationPage/components/SearchInput.tsx
  src/pages/SelectLocationPage/components/SearchResultItem.tsx
  src/pages/SelectLocationPage/components/SearchResultList.tsx
  src/pages/SelectLocationPage/components/searchInput.module.scss
  src/pages/SelectLocationPage/components/searchResultItem.module.scss
  src/pages/SelectLocationPage/page/index.tsx
  src/pages/SelectLocationPage/page/selectLocation.module.scss
  src/store/useLocationInfoStore.ts
  src/types/locationInfo.d.ts
  src/utils/calculateDistance.ts
  src/utils/drawMap.ts
  src/utils/formatDate.ts
  src/utils/geocoding.ts
  src/utils/truncation.ts
Labels: 🐛 BUG, 🚀 FEAT, STYLE, 정재호

#116 Feat: 그룹 생성 페이지 api 연동
  src/App.tsx
  src/api/apiRoutes.ts
  src/api/fetcher.ts
  src/api/googleMapLoader.ts
  src/api/group/postCreateGroup.ts
  src/api/user/postUserInformation.ts
  src/assets/images/arrivalPin.png
  src/components/buttons/Button.stories.tsx
  src/components/headers/CalendarHeader.tsx
  src/components/headers/calendarHeader.module.scss
  src/pages/CreateGroupPage/components/GroupNameInput.tsx
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/CreateGroupSchedulePage/page/index.tsx
  src/pages/CreateMySchedulePage/page/index.tsx
  src/pages/FindPage/page/index.tsx
  src/pages/FriendManagementPage/page/index.tsx
  src/pages/LocationSharingPage/components/GroupMemberItem.tsx
  src/pages/LocationSharingPage/components/groupMemberItem.module.scss
  src/pages/LocationSharingPage/page/index.tsx
  src/pages/LocationSharingPage/page/locationSharing.module.scss
  src/pages/LoginPage/components/find.module.scss
  src/pages/LoginPage/page/login.module.scss
  src/pages/MyCalendarPage/page/index.tsx
  src/pages/RegisterAccountPage/page/index.tsx
  src/pages/RegisterPage/page/index.tsx
  src/pages/StartPage/startPage.module.scss
  src/types/get.d.ts
  src/types/locationInfo.d.ts
  src/utils/drawMap.ts
  src/utils/geocoding.ts
Labels: 🚀 FEAT, 🛠️ FIX, 정재호

#123 Hotfix: 달력 페이지에서 사용되는 달력 컴포넌트 type === "view"일때 선택된 날짜의 값을 저장할 수 있도록 하는 set함수 props에 추가
  src/components/calendar/Calendar.tsx
  src/pages/MyCalendarPage/page/index.tsx
Labels: 🚨 HOTFIX, 정재호

#118 Style: 일정 수정 페이지 퍼블리싱
  src/App.tsx
  src/components/buttons/Button.stories.tsx
  src/components/createSchedule/Inputs.module.scss
  src/components/createSchedule/LocationBox.tsx
  src/components/createSchedule/MemberBox.tsx
  src/components/createSchedule/NoteBox.tsx
  src/components/createSchedule/TitleBox.tsx
  src/components/headers/HasOnlyRightIconHeader.tsx
  src/pages/CreateGroupPage/page/index.tsx
  src/pages/CreateGroupSchedulePage/page/index.tsx
  src/pages/CreateMySchedulePage/page/index.tsx
  src/pages/EditGroupSchedulePage/page/index.tsx
  src/pages/EditMySchedulePage/page/editMySchedule.module.scss
  src/pages/EditMySchedulePage/page/index.tsx
  src/pages/FindPage/page/index.tsx
  src/pages/FriendManagementPage/page/index.tsx
  src/pages/MyScheduleDetailPage/components/Boxes.module.scss
  src/pages/RegisterAccountPage/page/index.tsx
Labels: STYLE, 이수현

#120 Style: 그룹 달력 페이지 퍼블리싱
  src/components/buttons/goLogin.module.scss
  src/components/calendarPage/EventCard.stories.tsx
  src/components/calendarPage/EventCard.tsx
  src/components/calendarPage/eventCard.module.scss
  src/pages/GroupCalendarPage/page/groupCalendarPage.module.scss
  src/pages/GroupCalendarPage/page/index.tsx
  src/pages/LoginPage/page/index.tsx
  src/pages/LoginPage/page/login.module.scss
  src/pages/MyCalendarPage/page/index.tsx
  src/pages/MyCalendarPossiblePage/page/index.tsx
  src/pages/RegisterPage/page/index.tsx
  src/pages/RegisterPage/page/register.module.scss
  src/pages/StartPage/index.tsx
  src/pages/StartPage/startPage.module.scss
Labels: STYLE, 이수현

#126 Style: 그룹 달력 가능한 날짜 보기 페이지 퍼블리싱
  src/assets/Icons/calendar/Icon_crown_white.svg
  src/pages/GroupCalendarPossiblePage/components/DateCard.tsx
  src/pages/GroupCalendarPossiblePage/components/MemberCard.tsx
  src/pages/GroupCalendarPossiblePage/components/PossibleMember.tsx
  src/pages/GroupCalendarPossiblePage/components/RankCard.tsx
  src/pages/GroupCalendarPossiblePage/components/TabComponent.tsx
  src/pages/GroupCalendarPossiblePage/components/card.module.scss
  src/pages/GroupCalendarPossiblePage/components/possible.module.scss
  src/pages/GroupCalendarPossiblePage/components/tabComponent.module.scss
  src/pages/GroupCalendarPossiblePage/page/groupCalendarPossible.module.scss
  src/pages/GroupCalendarPossiblePage/page/index.tsx
  src/types/get.d.ts
Labels: STYLE, 이수현

#127 Feat: 그룹 멤버 목록 페이지 api 연동(그룹 멤버 목록 조회, 친구 요청, 친구 요청 취소, 친구 수락, 친구 거절, 그룹 탈퇴, 그룹 삭제, 그룹 강제 탈퇴)
  src/api/apiRoutes.ts
  src/api/fetcher.ts
  src/api/friend/deleteCancelRequestFriend.ts
  src/api/friend/deleteRejectRequestFriend.ts
  src/api/friend/postAcceptRequestFriend.ts
  src/api/friend/postRequestFriend.ts
  src/api/group/deleteForcedWithdrawalFromGroup.ts
  src/api/group/deleteGroup.ts
  src/api/group/deleteLeaveGroup.ts
  src/api/group/getGroupMemberList.ts
  src/pages/GroupMemberPage/components/MemberItem.tsx
  src/pages/GroupMemberPage/components/MemberList.tsx
  src/pages/GroupMemberPage/components/memberItem.module.scss
  src/pages/GroupMemberPage/components/memberList.module.scss
  src/pages/GroupMemberPage/page/groupMember.module.scss
  src/pages/GroupMemberPage/page/index.tsx
  src/pages/GroupPage/components/GroupOptions.tsx
  src/pages/GroupPage/page/index.tsx
  src/pages/InviteGroupMemberPage/components/FriendItem.tsx
  src/pages/InviteGroupMemberPage/components/SearchBox.tsx
  src/pages/InviteGroupMemberPage/page/index.tsx
  src/pages/RegisterAccountPage/page/index.tsx
  src/types/calendar.d.ts
  src/types/chatting.d.ts
  src/types/friend.d.ts
  src/types/get.d.ts
  src/types/group.d.ts
  src/types/user.d.ts
Labels: 🚀 FEAT, 정재호

#133 Hotfix: api 연동 테스트 문제 해결 및 페이지 레이아웃 수정
  src/api/group/deleteForcedWithdrawalFromGroup.ts
  src/api/group/deleteGroup.ts
  src/api/group/deleteLeaveGroup.ts
  src/components/headers/HasOnlyRightIconHeader.tsx
  src/components/headers/HasTwoIconHeader.tsx
  src/pages/GroupMemberPage/components/MemberItem.tsx
  src/pages/GroupMemberPage/components/memberItem.module.scss
  src/pages/GroupPage/components/groupOptions.module.scss
  src/pages/GroupPage/page/index.tsx
Labels: 🐛 BUG, 🚨 HOTFIX, 정재호
